### ISSUE TITLE
[JOSS] Julia style guide

### ISSUE THREAD

**Issue by matbesancon** [fsobral/RAFF.jl#10]
`RAFF.SortFun!`
From Julia style [guide](https://docs.julialang.org/en/v1/manual/style-guide/#Style-Guide-1), use CamelCase style only for modules and types, use `snake_case` with lower letters and underscores for functions, values, etc

**Comment by matbesancon** [comment]
Same thing for `setRAFFOutputLevel, setLMOutputLevel`.
This issue is raised as part of https://github.com/openjournals/joss-reviews/issues/1385

**Comment by fsobral** [comment]
You are right. Fixed in commit 89480d6f77ebb846577589616ca5117074bd2876. Unfortunately, I have incorrectly mentioned issue 7, instead of issue 10. But the problem was fixed.

**Comment by matbesancon** [comment]
Given that the name changes are breaking, it is recommended to change the minor version (in that case to 0.5.0)

**Comment by fsobral** [comment]
Thanks. I didn't know about this. We have updated to v0.5.0. The documentation has also been fixed, due to #9 .
