### ISSUE TITLE
[JOSS] Merge JOSS branch

### ISSUE THREAD

**Issue by matbesancon** [fsobral/RAFF.jl#13]
The structure of the `JOSS` branch is very different from the normal repo. The `joss` branch should have the same structure as the master branch (that of a Julia package), with a `paper` folder containing the paper.md and .bib files.

This issue is raised as part of: https://github.com/openjournals/joss-reviews/issues/1385

**Comment by fsobral** [comment]
Solved!

**Comment by fsobral** [comment]
Dear @matbesancon . Although we have made this change, now the RAFF version in the branch `joss` does not follow the `master` branch. To do so, we will always have to merge it manually into `joss`, so it becomes up-to-date. Do you have a better alternative to this? We think that there is no sense to have a `joss` directory inside the package's files, but that could be a solution...

**Comment by matbesancon** [comment]
@fsobral you can manually merge regularly, but the key point is that the structure is now identical (even if joss is a bit late on master).

Also, once the paper is finished, it will not be problematic to merge joss into master

**Comment by fsobral** [comment]
Ok. Thanks for the suggestion.
