### ISSUE TITLE
[JOSS] add contribution guidelines

### ISSUE THREAD

**Issue by matbesancon** [fsobral/RAFF.jl#14]
The authors should add some general guidelines for people who want to contribute by either submitting PRs or issues. See https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements
How do people reach out? On the repo or on another platform?

This issue is raised as part of https://github.com/openjournals/joss-reviews/issues/1385

**Comment by fsobral** [comment]
Thank you for the suggestion. I have added a 'Contribution' section in the `README`.
