### ISSUE TITLE
[JOSS] Gradient function signature

### ISSUE THREAD

**Issue by matbesancon** [fsobral/RAFF.jl#17]
From the documentation tutorial:
```
julia> gmodel(x, t, g)=begin
          g[1] = t[1]^2
          g[2] = 1.0
          return g
       end
```

Following the Julia style guide, the function could have a bang `gmodel!` to indicate it is
modifying its arguments. Moreover, the mutated argument is preferred placed first, as in `gmodel!(g, x, t)` 

Issue created for https://github.com/openjournals/joss-reviews/issues/1385

**Comment by fsobral** [comment]
@matbesancon We have fixed this issue in the documentation and in the whole code as well. The version has been updated to v0.6.0, since all the signatures of `gmodel` had to be changed.
