### ISSUE TITLE
[JOSS] Project.toml version mismatch

### ISSUE THREAD

**Issue by matbesancon** [fsobral/RAFF.jl#8]
This issue is raised as part of the review process for https://github.com/openjournals/joss-reviews/issues/1385

The Project.toml file still has 0.4.0 as version number, it should be changed to 0.4.1 which corresponds to the latest release

**Comment by fsobral** [comment]
Thank you. I have updated both Project and the tag names to v0.4.2.

**Comment by matbesancon** [comment]
Great!
