### ISSUE TITLE
[JOSS] installation instruction

### ISSUE THREAD

**Issue by matbesancon** [fsobral/RAFF.jl#9]
Since the package is not installable as registered packages for now, either register it (Registrator would be the best option) or add the installation steps at the beginning of the README

**Comment by matbesancon** [comment]
This issue is raised as part of https://github.com/openjournals/joss-reviews/issues/1385

**Comment by fsobral** [comment]
Done. `RAFF` has been added to Julia General package list. Now it is possible to install it by typing `add RAFF`.
